# Generated by Django 5.2.1 on 2026-02-11 09:19

import flowcontrol.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='condition',
            field=models.TextField(blank=True, default='', help_text='A Django template variable expression. Context contains `object`.', validators=[flowcontrol.utils.validate_template_condition], verbose_name='Condition Expression'),
        ),
        migrations.AlterField(
            model_name='flowrun',
            name='outcome',
            field=models.CharField(blank=True, choices=[('complete', 'Complete'), ('aborted', 'Aborted'), ('errored', 'Errored'), ('obsolete', 'Obsolete'), ('canceled', 'Canceled')], default='', max_length=20, verbose_name='Outcome'),
        ),
    ]
