# Generated by Django 5.2.1 on 2026-05-11 07:33

import django.db.models.deletion
import flowcontrol.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('flowcontrol', '0002_trigger_condition_alter_flowrun_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='condition',
            field=models.TextField(blank=True, default='', help_text='Cancels the run if this condition is not met during execution.', validators=[flowcontrol.utils.validate_template_condition], verbose_name='Condition to keep during run'),
        ),
        migrations.AddField(
            model_name='flow',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=flowcontrol.models.core.get_content_type_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
