# Generated by Django 6.0.3 on 2026-05-11 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcontrol', '0003_flow_condition_flow_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitForTrigger',
            fields=[
                ('flowaction_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='flowcontrol.flowaction')),
            ],
            options={
                'abstract': False,
            },
            bases=('flowcontrol.flowaction',),
        ),
        migrations.RemoveConstraint(
            model_name='trigger',
            name='unique_flow_trigger',
        ),
        migrations.AddField(
            model_name='flowrun',
            name='waiting_trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_runs', to='flowcontrol.trigger', verbose_name='Waiting on trigger'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='create_flow',
            field=models.BooleanField(default=True, help_text='Whether to create a new flow run when this trigger is received.', verbose_name='Create flow run on trigger'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='flowcontrol.flow', verbose_name='Flow'),
        ),
        migrations.AddConstraint(
            model_name='trigger',
            constraint=models.UniqueConstraint(condition=models.Q(('flow__isnull', False)), fields=('flow', 'trigger'), name='unique_flow_trigger'),
        ),
        migrations.AddConstraint(
            model_name='trigger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('create_flow', True), ('flow__isnull', False)), ('create_flow', False), _connector='OR'), name='flow_required_if_create_flow'),
        ),
        migrations.AddField(
            model_name='waitfortrigger',
            name='trigger',
            field=models.ForeignKey(help_text='The trigger that this action will wait for before proceeding.', on_delete=django.db.models.deletion.PROTECT, related_name='wait_actions', to='flowcontrol.trigger', verbose_name='Trigger to wait for'),
        ),
        migrations.AddField(
            model_name='flowrun',
            name='waiting_trigger_match_object',
            field=models.BooleanField(default=True, verbose_name='Waiting trigger requires object match'),
        ),
        migrations.AddField(
            model_name='waitfortrigger',
            name='require_object',
            field=models.BooleanField(default=True, help_text='If checked, the trigger will only be processed if it matches the flow runs object.', verbose_name='Require object'),
        ),
    ]
