# Generated by Django 6.0.3 on 2026-05-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcontrol', '0004_waitfortrigger_remove_trigger_unique_flow_trigger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlert',
            fields=[
                ('flowaction_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='flowcontrol.flowaction')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('templated', models.BooleanField(default=False)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=('flowcontrol.flowaction',),
        ),
    ]
