# Generated by Django 6.0.3 on 2026-05-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcontrol', '0005_emailalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='reset_to_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='flowcontrol.flowaction', verbose_name='Reset to flow action'),
        ),
    ]
