site_name: Django Flowcontrol
repo_url: https://github.com/okfde/django-flowcontrol
theme:
  name: readthedocs
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        # # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google
            show_source: false
            show_docstring_parameters: true
            show_root_heading: false
            heading_level: 3
nav:
  - "Django-Flowcontrol": 'index.md'
  # - "Getting started": 'tutorial.md'
  - "Concepts": 'concepts.md'
  - "Custom actions": 'actions.md'
  - "API Reference": 'api.md'

